### PR TITLE
Update 1-how-it-works.md

### PR DESCRIPTION
**Pull request by amritnagi**
Hi Adriaan.. some changes - feel free to cherry pick what you want to keep!

### CODE REVIEW

**Review by adriaandotcom — APPROVED** [review]
Great work, thanks, way better. Only need to find a way to show the tables on mobile.

**Comment by amritnagi** [comment]
I think the only way is using CSS?

Maybe this will work? https://flaviocopes.com/css-responsive-table/

**Comment by amritnagi** [comment]
https://css-tricks.com/accessible-simple-responsive-tables/

Approach 3 might be better?

**Comment by adriaandotcom** [comment]
Solved it like this, with scrolling indeed: https://github.com/simpleanalytics/docs.simpleanalytics.io/commit/594e71c2e558888b0814a6585a8250c0de0eec30

**Comment by adriaandotcom** [comment]
Thanks Amrit, really appreciate it.

**Pull request merged**
